[package]
name = "tmf-client"
version = "0.1.1"
edition = "2021"
authors = ["Ryan Ruckley <rruckley@gmail.com"]
description = "A Rust client library for TMF conformant APIs"
license = "Apache-2.0"

[dependencies]
env_logger = "0.11.3"
oauth2 = "4.4.2"
reqwest = {version = "0.12.2", features = ["blocking"]}
serde = "1.0"
serde_json = "1.0"
tmflib = "0.1.16"
