[package]
name = "tmf-client"
version = "0.1.0"
edition = "2021"
authors = ["Ryan Ruckley <rruckley@gmail.com"]
description = "A Rust client library for TMF conformant APIs"

[dependencies]
env_logger = "0.11.1"
reqwest = "0.11.24"
tmflib = { git = "https://github.com/rruckley/tmflib.git"}
